

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pnapaa
      - POSTGRES_SERVER=db  # меняем localhost на имя сервиса
      - POSTGRES_PORT=5432
      - POSTGRES_DB=projecthub
      - MINIO_ENDPOINT=minio:9000  # меняем localhost на имя сервиса
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - db
      - minio
    volumes:
      - ./src:/app/src

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=projecthub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pnapaa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: